config/routes.rb
Rails.application.routes.draw do

  resources :uploaded_files

  resources :tableau_users

  resources :tableaus, path: '/tableau-dashboards'

  resources :extra_fields do
    collection do
      post :add_row, to: 'extra_fields#add_row'
      get 'remove_row/:group_id', to: 'extra_fields#remove_row'
      post :order_row, to: 'extra_fields#order_row'
    end
  end

  resources :pages_groups

  resources :microsites_groups

  get 'microsites_groups/unlinkmicrosite/:microsite_id/:group_id' => 'microsites_groups#unlinkmicrosite'

  get 'microsites_groups/addexistingmicrositestogroups/:group_id' => 'microsites_groups#addexistingmicrositestogroups'
  patch 'microsites_groups/addexistingmicrositestogroups/:group_id' => 'microsites_groups#addexistingmicrositestogroups'
  get 'microsites_groups/listpagesbymicrositeandgroup/:microsite_id/:group_id' => 'microsites_groups#listpagesbymicrositeandgroup'
  get 'microsites/unlink_client/:microsite_id/:client_id' => 'microsites#unlink_client'
  get 'microsites/:id/:pid/default_page' => 'microsites#default_page'

  resources :survey_groups
  get 'survey_groups/addexistingsurveystogroups/:group_id' => 'survey_groups#addexistingsurveystogroups'
  patch 'survey_groups/addexistingsurveystogroups/:group_id' => 'survey_groups#addexistingsurveystogroups'
  get 'survey_groups/unlinkgroup/:survey_id/:group_id' => 'survey_groups#unlinkgroup'

  resources :groups do
    get :autocomplete_group_name, :on => :collection
    get :autocomplete_user_username, :on => :collection

    get 'upload_users' 
    post 'upload_users'
    get 'unlink_user/:user_id' => 'groups#unlink_user'
    patch 'addExistingUsers'

    resources :variables, controller: :groups_variables
  end
  get 'file_mangers/all_files'

  get 'file_mangers/new_file'

  post 'file_mangers/create_file'

  resources :folders do
    resources :file_mangers
  end

  scope '/client' do
    get 'dashboard/:id' => 'page#client_dashboard'
    get 'tableau/:id/:task' => 'page#client_dashboard'
    get 'tableau/ticket' => 'page#client_dashboard'
    get ':id'=> 'admin#showClient'
    patch ':id' => 'admin#showClient'
  end

  scope '/take' do 
    get 'surveys' => 'played_surveys#surveys'
    get 'survey/:survey_id' => 'played_surveys#survey'
    get 'survey/:survey_id/:section_id' => 'played_surveys#survey'
    patch 'savesurvey/:section_id' => 'played_surveys#savesurvey'
  end

  resources :microsites do
    get :autocomplete_microsite_title, :on => :collection     
    member do

      get 'newcmspage/:template_id' => 'admin#newcmspage'
      
      get 'addexistingsurveys' => 'admin#addexistingsurveys'
      patch 'addexistingsurveys' => 'admin#addexistingsurveys'

      post 'create_cmspage' => 'admin#create_cmspage'
      patch 'create_cmspage' => 'admin#create_cmspage'
      get 'editpage/:cms_page_id/:template_id' => 'admin#editpage'
      patch 'update_cmspage/:cms_page_id' => 'admin#update_cmspage'

      get 'addexistingpages' => 'microsites#addexistingpages'
      patch 'addexistingpages' => 'microsites#addexistingpages'
      get 'unlinkcmspage/:page_id' => 'microsites#unlinkcmspage'

    end
  end

  resources :surveys do
    get :autocomplete_survey_name, :on => :collection 
  end
 
  post 'microsites/index' => 'microsites#index'
  get 'page/unpublished'

  mount Ckeditor::Engine => '/ckeditor'
  resources :played_surveys

  get 'page/show'
  resources :qfields
  get 'question/new/:section_id' =>'question#new'
  post 'question/new'
  post 'question/create'

  post 'qfield/delete/:id' => 'qfields#destroy'

  get 'admin/listroles' => 'admin#listroles'

  get 'admin/clients' => 'admin#listClients'

  get 'admin/editrole/:id/:role_id' => 'admin#editrole'

  patch 'admin/:id/updaterole' => 'admin#updaterole'

  get 'admin/listRoleCapability/:id/:role_id' => 'admin#listRoleCapability'

  post 'admin/setPermition/:id/:role_id' => 'admin#setPermition'

  get 'admin/unauthorised' => 'admin#unauthorised'

  get 'admin/taken_surveys' => 'admin#played_surveys'

  get 'question/field_type' => 'question#field_type'

  post 'question/field_type' => 'question#field_type'

  get 'admin/importuserscsv' => 'admin#importuserscsv'
  post 'admin/processuserscsv' => 'admin#processuserscsv'

  post 'admin/importusers' => 'admin#importusers'

  get 'admin/exportcsv' => 'admin#exportcsv'
  get 'admin/exportxls' => 'admin#exportxls'

  get 'admin/assign_survey' => 'admin#assign_survey_to_users'
  post 'admin/sending_group_invitation_users' => 'admin#sending_group_invitation_users'
 
  post '/admin/assign_survey_to_microsite' => 'admin#assign_survey_to_microsite'

  get 'admin/clients/new' => 'admin#newclient'
  get 'admin/clients/:id/edit' => 'admin#editclient'
  patch 'admin/clients/create' => 'admin#createclient'
  patch 'admin/clients/update' => 'admin#updateclient'

 
  
  resources :section
  resources :question
  resources :page
  resources :cms_page

  resources :cms_pages do
    get :autocomplete_cms_page_title, :on => :collection  
   post 'managegroup/:group_id' => 'cms_pages#managegroup'
  end

  resources :reports do
    collection do
      get :iframe
      get :javascript
      post :login
      get :logout
      get :access_denied
    end
  end

    

  post 'section/update/:id' => 'section#update'
  post 'section/create/:id' => 'section#create'
  get 'section/:id/new' => 'section#new'
  get 'section/:id/delete' => 'section#delete'

  get 'admin/microsites/:client_id' => 'admin#microsites'

  

  get 'question/:id/new' => 'question#new'

  post 'question/update' => 'question#update'

  get 'question/:id/delete/:survey_id' => 'question#delete'

  get 'question/:id/edit/:survey_id' => 'question#edit'
  post 'question/:id/edit/:survey_id' => 'question#edit'

  get 'admin/:id/editsurvey' => 'admin#editsurvey'
  get 'surveys/:id/destroy' => 'surveys#destroy'
  post 'surveys/:id/update' => 'surveys#update'

  get 'admin/clonepage/:page_id' => 'admin#clonepage'
  delete 'admin/deletepage/:page_id' => 'admin#deletepage'
  
  get  'surveyresults' => 'admin#survey_results'

 
  get 'admin/home' => 'admin#home'

  get 'admin/users' => 'admin#listUsers'
  put 'admin/edit_user_individual' => 'admin#edit_user_individual'
  post 'admin/bulkupdaterole'  =>  'admin#bulkupdaterole'
  get 'admin/delUser/:id' => 'admin#delUser'
  post 'admin/sendinvitationuser'  =>  'admin#sendinvitationuser'

  get 'admin/addUser', to: 'admin#addUser'
  post 'admin/addUser', to: 'admin#addUser'

  get 'admin/editUser/:id', to:'admin#editUser', as: :admin_editUser
  post 'admin/editUser/:id', to:'admin#editUser'

  get 'admin/upload_users', to: 'admin#upload_users'
  post 'admin/upload_users', to: 'admin#upload_users'

  get 'admin/addSurvey', to: 'admin#addSurvey'
  get 'admin/addSurvey/:client_id', to: 'admin#addSurvey'
  post 'admin/addSurvey', to: 'admin#addSurvey'
  get 'admin/manageSurvey', to: 'admin#manageSurvey'
  post 'admin/manageSurvey', to: 'admin#manageSurvey'
  get 'admin/buildsurvey/:id', to: 'admin#buildsurvey'
  get 'admin/survey_exports/:id', to: 'admin#survey_exports'
  get 'admin/unlinksurvey/:survey_id/:microsite_id', to: 'admin#unlinksurvey'

  resources :ext_users do
    resources :variables, controller: 'users_variables'
  end

  get 'two_factor_authentication', to: 'page#enterotp'
  get '/confirm/:id/:otp', to: 'page#check_two_factor_authentication'
  put 'check_two_factor_authentication', to: 'page#check_two_factor_authentication'
  post 'check_two_factor_authentication', to: 'page#check_two_factor_authentication'

  root 'admin#home' 
  devise_for :users, controllers: {  
      registrations:'users/registrations',
      sessions:'users/sessions',
      passwords:'users/passwords',
      confirmations:'users/confirmations',
      mailer:'users/mailer',
      shared:'users/shared',
      invitations:'users/invitations'
  }  do

  post 'two_factor_authentication' => 'users/sessions#check_two_factor_authentication'

  end
  
  resources :variables  

    
 

  get 'admin/accessmanage' => 'admin#accessmanage'

  post 'admin/create_slug' => 'admin#create_slug'
  get 'admin/newcmspage' => 'admin#newcmspage'
  get 'admin/newcmspage/:template_id' => 'admin#newcmspage'

  post 'admin/create_cmspage' => 'admin#create_cmspage'
  patch 'admin/create_cmspage' => 'admin#create_cmspage'

  get 'admin/listcmspages' => 'admin#listcmspages'
  post 'admin/listcmspages' => 'admin#listcmspages'
  get 'admin/editpage/:cms_page_id' => 'admin#editpage'

  get 'page_col/add_row/:page_id' => 'page#add_row'
  patch 'admin/update_cmspage/:cms_page_id' => 'admin#update_cmspage'
  get ':client_slug/:microsite_slug' => 'page#preview_microsite', as: :client_microsite
  get ':client_slug/:microsite_slug/:cms_page_slug' => 'page#preview_microsite'
  get ':slug' => 'page#cms'
  get ':slug/:type' => 'page#cms' 

  

end

app/models/file_manger.rb
class FileManger < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :attachment, presence: true # Make sure the owner's name is present.

  before_save :update_attachment_attributes

  belongs_to :folder
  belongs_to :user, :dependent => :destroy

  private

  def update_attachment_attributes
    if attachment.present? && attachment_changed?
      self.name = attachment.file.original_filename    
      self.size = attachment.file.size
    end
	end

end

app/controllers/file_mangers_controller.rb
class FileMangersController < ApplicationController
 before_action :authenticate_user!
 before_action :check_permition
 before_action :set_file_manger, only: [:show, :edit, :update, :destroy]
 # layout "filesfolder"
  layout "dashboard"


  # GET /file_mangers
  # GET /file_mangers.json
  def index
   # @file_mangers = FileManger.where(:user_id=> current_user.id)

    ff = Folder.where(:user_id=> current_user.id)
    if ff.present?
      folder = Folder.find(params[:folder_id])
      @file_mangers = folder.file_mangers
    else
      flash[:notice] = 'Access Denied'
      redirect_to folders_path
    end

  end


  def all_files
    @files = FileManger.where(:user_id=> current_user.id)
  end


  def new_file
  @cc = Folder.where(:user_id=> current_user.id)

  end

   def create_file
  @newfile =   FileManger.create(:name => params[:name], :attachment=>params[:attachment],:folder_id=> params[:folder_id],:user_id => current_user.id)
    if @newfile.save
    flash[:notice] = 'File saved successfully'
    redirect_to folders_path
    else
    flash[:notice] = 'File not saved successfully'
    redirect_to folders_path
    end


  end


  # GET /file_mangers/1
  # GET /file_mangers/1.json
  def show
      folder = Folder.find(params[:folder_id])
      @file_manger = folder.file_mangers.find(params[:id])
  end

  # GET /file_mangers/new
  def new

    folder = Folder.find(params[:folder_id])
    #2nd you build a new one
    @file_manger = folder.file_mangers.build
    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @file_manger }
    end
  end

  # GET /file_mangers/1/edit
  def edit
   folder = Folder.find(params[:folder_id])
   @file_manger = folder.file_mangers.find(params[:id])
  end

  # POST /file_mangers
  # POST /file_mangers.json
def create
    #1st you retrieve the post thanks to params[:post_id]
    folder = Folder.find(params[:folder_id])
    #2nd you create the comment with arguments in params[:comment]
    @file_manger = folder.file_mangers.create(file_manger_params)

    respond_to do |format|
      if @file_manger.save
        #1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
        format.html { redirect_to([@file_manger.folder, @file_manger], :notice => 'File was successfully created.') }
        #the key :location is associated to an array in order to build the correct route to the nested resource comment
        format.json  { render :json => @file_manger, :status => :created, :location => [@file_manger.folder, @file_manger] }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @file_manger.errors, :status => :unprocessable_entity }
      end
    end
end

  # PATCH/PUT /file_mangers/1
  # PATCH/PUT /file_mangers/1.json
  def update

         folder = Folder.find(params[:folder_id])
    #2nd you retrieve the comment thanks to params[:id]
      @file_manger = folder.file_mangers.find(params[:id])
       respond_to do |format|
      if @file_manger.update_attributes(file_manger_params)
        format.html { redirect_to([@file_manger.folder, @comment], :notice => 'File was successfully update.') }
        format.json  { render :json => @file_manger, :status => :created, :location => [@file_manger.folder, @file_manger] }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @file_manger.errors, :status => :unprocessable_entity }
      end
 end




  end

  # DELETE /file_mangers/1
  # DELETE /file_mangers/1.json
  def destroy
  
     #1st you retrieve the post thanks to params[:post_id]
    folder = Folder.find(params[:folder_id])
    #2nd you retrieve the comment thanks to params[:id]
    @file_manger = folder.file_mangers.find(params[:id])

# Rails.logger.warn @file_manger.inspect
    @file_mangers.destroy
    respond_to do |format|
      #1st argument reference the path /posts/:post_id/comments/
      format.html { redirect_to(folder_file_mangers_url) }
      format.json { head :no_content }
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_manger
            #    folder = Folder.where(:id => params[:folder_id], :user_id => current_user.id)
            # if folder.present?
            # @file_mangers = folder.file_mangers.find(params[:id])
            # else
            # redirect_to folders_path
            # end



 ff = Folder.where(:user_id=> current_user.id)
    if ff.present?
      folder = Folder.find(params[:folder_id])
            @file_mangers = folder.file_mangers.find(params[:id])
    else
       flash[:notice] = 'Access Denied'
      redirect_to folders_path
    end




    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_manger_params
      #Rails.logger.warn params[:file_manger][:attachment].original_filename
      #Rails.logger.warn "test2"
      params.require(:file_manger).permit(:name, :size, :attachment,:folder_id).merge(:user_id => current_user.id)
      # .merge(:name=> params[:file_manger][:attachment].original_filename)
    end

   private  
  def check_permition
    if current_user != nil
      if !current_user.can? params[:action].to_sym, :filemanager
      flash[:alert] = [['You are not authorised to access this page']]
      redirect_to :controller => :admin, :action =>:home
      end
    end 
  end  
     
end

app/helpers/file_mangers_helper.rb
module FileMangersHelper
end

app/views/file_mangers/_form.html.erb
   <div class="panel-body">
                               <p id="notice"><%= notice %></p>          
        <%#= form_for @folder, html: { multipart: true, class: "form-horizontal"} do |f| %>
        <%= form_for([@file_manger.folder, @file_manger]) do |f| %>

                                 <% if @file_manger.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.messages.not_saved', count: @file_manger.errors.count, resource: t(:comment)) %></h2>

      <ul>
      <% @file_manger.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
                                    <div class="form-group">
                                                <%= f.label :name, class: "col-md-2 control-label" %>
                                                <div class="col-md-10">
                                              <%= f.text_field :name, class: "form-control" %>
                                                </div>
                                              </div>
 <div class="form-group">
                                                <%= f.label :attachment, class: "col-md-2 control-label" %>
                                                <div class="col-md-10">
    <%= f.file_field :attachment, :required => true %>
                                                </div>
                                              </div>




                                            <div class="form-group m-b-0">
                                                <div class="col-sm-offset-3 col-sm-9">
                                           <%= f.submit t(:Save) , :class=> "btn btn-info waves-effect waves-light" %> 

                                                </div>
                                            </div>

                           
                                       <% end %>

                                    </div> <!-- panel-body -->
                         

app/views/file_mangers/all_files.html.erb
        <div class="row">
                            <div class="col-md-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Listing File
                                               <span class="pull-right"> 
                                                 <%= link_to t(:Back), :back %>
                                                </span>
                                        </h3>
                                    </div>
                                    <div class="panel-body">
                                        <div class="row">
                                          <p id="notice"><%= notice %></p>

                                            <div class="col-md-12 col-sm-12 col-xs-12">
                                                <div class="table-responsive">
                                                    <table class="table">
                                                <tr>
    <th><%= t(:NAME) %></th>
      <th><%= t(:Size) %></th>
      <th><%= t(:Attachment) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

    <% @files.each_with_index do |file_manger, index | %>
  <tr>
   <td><%= file_manger.name %>  
<!-- <input title="use this link in editor" type="text" class="copytext" value="<%#=  file_manger.attachment.url %>"  /> -->
   </td>
        <td><%= number_to_human_size(file_manger.size)     %>  </td>
        <td> <%= image_tag Icon.for_filename(file_manger.name) %>
<%#= image_tag Icon.for_ext '.jpg' %>

       <a target ="_blank" href="<%=  file_manger.attachment %>"><%= t(:DOWNLOAD_FILE) %></a>

        </td>
    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to t(:show), [file_manger.folder, file_manger] %></td>
    <!-- /posts/:post_id/comments/:id/edit -->
    <td><%= link_to t(:edit), edit_folder_file_manger_path(file_manger.folder, file_manger)%></td>
    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to t(:destroy), [file_manger.folder, file_manger], :confirm => t(:ARE_YOU_SURE), :method => :delete %></td>
  </tr>
<% end %>
                                                    </table>
                                                </div>
                                            </div>
<%#= link_to('New File',file_mangers_new_file_path, rel: "modal:open") %>


<%= link_to('New File',file_mangers_new_file_path,  :class =>"fancyajax") %>












                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- End row -->

app/views/file_mangers/edit.html.erb
<h1>Editing File Manger</h1>

<%= render 'form' %>

<!-- /posts/:post_id/comments/:id -->
<%= link_to t(:show), [@file_manger.folder, @file_manger] %> |
<!-- /posts/:post_id/comments/ -->
<%#= link_to t(:Back), file_mangers_path(@file_manger.post) %>

app/views/file_mangers/index.html.erb
        <div class="row">
                            <div class="col-md-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h3 class="panel-title trans-none"><%= t(:MANAGE_FILES) %>
                                               <span class="pull-right"> 
                                                 <%= link_to t(:Back), :back %>
                                                </span>
                                        </h3>
                                    </div>
                                    <div class="panel-body">
                                        <div class="row">
                                          <p id="notice"><%= notice %></p>

                                            <div class="col-md-12 col-sm-12 col-xs-12">
                                                <div class="table-responsive">
                                                    <table class="table">
                                                   <tr>
    <th><%= t(:NAME) %></th>
      <th><%= t(:Size) %></th>
      <th><%= t(:Attachment) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

    <% @file_mangers.each do |file_manger| %>
  <tr>
   <td><%= file_manger.name %>

   <!-- <input title="use this link in editor" type="text" class="copytext" value="<%#=  file_manger.attachment.url %>"  /> -->
 </td>
        <td><%= number_to_human_size(file_manger.size)     %>

  </td>
        <td> <%= image_tag Icon.for_filename(file_manger.name) %>
<%#= image_tag Icon.for_ext '.jpg' %>

       <a target ="_blank" href="<%=  file_manger.attachment %>"><%= t(:DOWNLOAD_FILE) %></a>

        </td>
    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to t(:show), [file_manger.folder, file_manger] %></td>
    <!-- /posts/:post_id/comments/:id/edit -->
    <td><%= link_to t(:edit), edit_folder_file_manger_path(file_manger.folder, file_manger)%></td>
    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to t(:destroy), [file_manger.folder, file_manger], :confirm => t(:ARE_YOU_SURE), :method => :delete %></td>
  </tr>
<% end %>
                                                    </table>
                                                </div>
                                            </div>
<%= link_to('New File',file_mangers_new_file_path, rel: "modal:open") %>


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- End row -->

app/views/file_mangers/new.html.erb
<h1>New File</h1>

<%= render 'form' %>

<!-- /posts/:post_id/comments/ -->
<%= link_to t(:Back), folder_file_mangers_path(@file_manger.folder)%>

app/views/file_mangers/new_file.html.erb
<%= form_tag(file_mangers_create_file_path, multipart: true) do %>
<%#= text_field_tag :name, nil, :placeholder => 'Enter Name of file' %>
<%= file_field_tag :attachment %>
<br>

<%#= debug @cc.inspect %>
<% if @cc.present? %>
    Folder:<%= select_tag :folder_id, options_from_collection_for_select(@cc, "id", "name"),  prompt: "Select Folder",:required => true %>
    <% else %>
Please create a folder first
<%#= link_to('New Folder', new_folder_path, rel: "modal:open") %>
<%= link_to('New Folder', new_folder_path,  :class =>"fancyajax") %>





<% end %>



<%= submit_tag t(:Upload), :class=> "btn btn-info waves-effect waves-light" %> 
<% end %>

app/views/file_mangers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @file_manger.name %>
</p>

<p>
  <strong><%= t(:Size) %>:</strong>
  <%= @file_manger.size %>
</p>

<p>
  <strong>Attachment:</strong>
  <%#= @file_manger.attachment %>
  <%= image_tag Icon.for_filename(@file_manger.name) %>
 <a t

<!-- /posts/:post_id/comments/:id/edit -->
<%= link_to t(:edit), edit_folder_file_manger_path(@file_manger.folder, @file_manger) %> |
<!-- /posts/:post_id/comments/ -->
<%= link_to t(:Back), folder_file_mangers_path(@file_manger.folder) %>