config/routes.rb
Rails.application.routes.draw do

  resources :uploaded_files

  resources :tableau_users

  resources :tableaus, path: '/tableau-dashboards'

  resources :extra_fields do
    collection do
      post :add_row, to: 'extra_fields#add_row'
      get 'remove_row/:group_id', to: 'extra_fields#remove_row'
      post :order_row, to: 'extra_fields#order_row'
    end
  end

  resources :pages_groups

  resources :microsites_groups

  get 'microsites_groups/unlinkmicrosite/:microsite_id/:group_id' => 'microsites_groups#unlinkmicrosite'

  get 'microsites_groups/addexistingmicrositestogroups/:group_id' => 'microsites_groups#addexistingmicrositestogroups'
  patch 'microsites_groups/addexistingmicrositestogroups/:group_id' => 'microsites_groups#addexistingmicrositestogroups'
  get 'microsites_groups/listpagesbymicrositeandgroup/:microsite_id/:group_id' => 'microsites_groups#listpagesbymicrositeandgroup'
  get 'microsites/unlink_client/:microsite_id/:client_id' => 'microsites#unlink_client'
  get 'microsites/:id/:pid/default_page' => 'microsites#default_page'

  resources :survey_groups
  get 'survey_groups/addexistingsurveystogroups/:group_id' => 'survey_groups#addexistingsurveystogroups'
  patch 'survey_groups/addexistingsurveystogroups/:group_id' => 'survey_groups#addexistingsurveystogroups'
  get 'survey_groups/unlinkgroup/:survey_id/:group_id' => 'survey_groups#unlinkgroup'

  resources :groups do
    get :autocomplete_group_name, :on => :collection
    get :autocomplete_user_username, :on => :collection

    get 'upload_users' 
    post 'upload_users'
    get 'unlink_user/:user_id' => 'groups#unlink_user'
    patch 'addExistingUsers'

    resources :variables, controller: :groups_variables
  end
  get 'file_mangers/all_files'

  get 'file_mangers/new_file'

  post 'file_mangers/create_file'

  resources :folders do
    resources :file_mangers
  end

  scope '/client' do
    get 'dashboard/:id' => 'page#client_dashboard'
    get 'tableau/:id/:task' => 'page#client_dashboard'
    get 'tableau/ticket' => 'page#client_dashboard'
    get ':id'=> 'admin#showClient'
    patch ':id' => 'admin#showClient'
  end

  scope '/take' do 
    get 'surveys' => 'played_surveys#surveys'
    get 'survey/:survey_id' => 'played_surveys#survey'
    get 'survey/:survey_id/:section_id' => 'played_surveys#survey'
    patch 'savesurvey/:section_id' => 'played_surveys#savesurvey'
  end

  resources :microsites do
    get :autocomplete_microsite_title, :on => :collection     
    member do

      get 'newcmspage/:template_id' => 'admin#newcmspage'
      
      get 'addexistingsurveys' => 'admin#addexistingsurveys'
      patch 'addexistingsurveys' => 'admin#addexistingsurveys'

      post 'create_cmspage' => 'admin#create_cmspage'
      patch 'create_cmspage' => 'admin#create_cmspage'
      get 'editpage/:cms_page_id/:template_id' => 'admin#editpage'
      patch 'update_cmspage/:cms_page_id' => 'admin#update_cmspage'

      get 'addexistingpages' => 'microsites#addexistingpages'
      patch 'addexistingpages' => 'microsites#addexistingpages'
      get 'unlinkcmspage/:page_id' => 'microsites#unlinkcmspage'

    end
  end

  resources :surveys do
    get :autocomplete_survey_name, :on => :collection 
  end
 
  post 'microsites/index' => 'microsites#index'
  get 'page/unpublished'

  mount Ckeditor::Engine => '/ckeditor'
  resources :played_surveys

  get 'page/show'
  resources :qfields
  get 'question/new/:section_id' =>'question#new'
  post 'question/new'
  post 'question/create'

  post 'qfield/delete/:id' => 'qfields#destroy'

  get 'admin/listroles' => 'admin#listroles'

  get 'admin/clients' => 'admin#listClients'

  get 'admin/editrole/:id/:role_id' => 'admin#editrole'

  patch 'admin/:id/updaterole' => 'admin#updaterole'

  get 'admin/listRoleCapability/:id/:role_id' => 'admin#listRoleCapability'

  post 'admin/setPermition/:id/:role_id' => 'admin#setPermition'

  get 'admin/unauthorised' => 'admin#unauthorised'

  get 'admin/taken_surveys' => 'admin#played_surveys'

  get 'question/field_type' => 'question#field_type'

  post 'question/field_type' => 'question#field_type'

  get 'admin/importuserscsv' => 'admin#importuserscsv'
  post 'admin/processuserscsv' => 'admin#processuserscsv'

  post 'admin/importusers' => 'admin#importusers'

  get 'admin/exportcsv' => 'admin#exportcsv'
  get 'admin/exportxls' => 'admin#exportxls'

  get 'admin/assign_survey' => 'admin#assign_survey_to_users'
  post 'admin/sending_group_invitation_users' => 'admin#sending_group_invitation_users'
 
  post '/admin/assign_survey_to_microsite' => 'admin#assign_survey_to_microsite'

  get 'admin/clients/new' => 'admin#newclient'
  get 'admin/clients/:id/edit' => 'admin#editclient'
  patch 'admin/clients/create' => 'admin#createclient'
  patch 'admin/clients/update' => 'admin#updateclient'

 
  
  resources :section
  resources :question
  resources :page
  resources :cms_page

  resources :cms_pages do
    get :autocomplete_cms_page_title, :on => :collection  
   post 'managegroup/:group_id' => 'cms_pages#managegroup'
  end

  resources :reports do
    collection do
      get :iframe
      get :javascript
      post :login
      get :logout
      get :access_denied
    end
  end

    

  post 'section/update/:id' => 'section#update'
  post 'section/create/:id' => 'section#create'
  get 'section/:id/new' => 'section#new'
  get 'section/:id/delete' => 'section#delete'

  get 'admin/microsites/:client_id' => 'admin#microsites'

  

  get 'question/:id/new' => 'question#new'

  post 'question/update' => 'question#update'

  get 'question/:id/delete/:survey_id' => 'question#delete'

  get 'question/:id/edit/:survey_id' => 'question#edit'
  post 'question/:id/edit/:survey_id' => 'question#edit'

  get 'admin/:id/editsurvey' => 'admin#editsurvey'
  get 'surveys/:id/destroy' => 'surveys#destroy'
  post 'surveys/:id/update' => 'surveys#update'

  get 'admin/clonepage/:page_id' => 'admin#clonepage'
  delete 'admin/deletepage/:page_id' => 'admin#deletepage'
  
  get  'surveyresults' => 'admin#survey_results'

 
  get 'admin/home' => 'admin#home'

  get 'admin/users' => 'admin#listUsers'
  put 'admin/edit_user_individual' => 'admin#edit_user_individual'
  post 'admin/bulkupdaterole'  =>  'admin#bulkupdaterole'
  get 'admin/delUser/:id' => 'admin#delUser'
  post 'admin/sendinvitationuser'  =>  'admin#sendinvitationuser'

  get 'admin/addUser', to: 'admin#addUser'
  post 'admin/addUser', to: 'admin#addUser'

  get 'admin/editUser/:id', to:'admin#editUser', as: :admin_editUser
  post 'admin/editUser/:id', to:'admin#editUser'

  get 'admin/upload_users', to: 'admin#upload_users'
  post 'admin/upload_users', to: 'admin#upload_users'

  get 'admin/addSurvey', to: 'admin#addSurvey'
  get 'admin/addSurvey/:client_id', to: 'admin#addSurvey'
  post 'admin/addSurvey', to: 'admin#addSurvey'
  get 'admin/manageSurvey', to: 'admin#manageSurvey'
  post 'admin/manageSurvey', to: 'admin#manageSurvey'
  get 'admin/buildsurvey/:id', to: 'admin#buildsurvey'
  get 'admin/survey_exports/:id', to: 'admin#survey_exports'
  get 'admin/unlinksurvey/:survey_id/:microsite_id', to: 'admin#unlinksurvey'

  resources :ext_users do
    resources :variables, controller: 'users_variables'
  end

  get 'two_factor_authentication', to: 'page#enterotp'
  get '/confirm/:id/:otp', to: 'page#check_two_factor_authentication'
  put 'check_two_factor_authentication', to: 'page#check_two_factor_authentication'
  post 'check_two_factor_authentication', to: 'page#check_two_factor_authentication'

  root 'admin#home' 
  devise_for :users, controllers: {  
      registrations:'users/registrations',
      sessions:'users/sessions',
      passwords:'users/passwords',
      confirmations:'users/confirmations',
      mailer:'users/mailer',
      shared:'users/shared',
      invitations:'users/invitations'
  }  do

  post 'two_factor_authentication' => 'users/sessions#check_two_factor_authentication'

  end
  
  resources :variables  

    
 

  get 'admin/accessmanage' => 'admin#accessmanage'

  post 'admin/create_slug' => 'admin#create_slug'
  get 'admin/newcmspage' => 'admin#newcmspage'
  get 'admin/newcmspage/:template_id' => 'admin#newcmspage'

  post 'admin/create_cmspage' => 'admin#create_cmspage'
  patch 'admin/create_cmspage' => 'admin#create_cmspage'

  get 'admin/listcmspages' => 'admin#listcmspages'
  post 'admin/listcmspages' => 'admin#listcmspages'
  get 'admin/editpage/:cms_page_id' => 'admin#editpage'

  get 'page_col/add_row/:page_id' => 'page#add_row'
  patch 'admin/update_cmspage/:cms_page_id' => 'admin#update_cmspage'
  get ':client_slug/:microsite_slug' => 'page#preview_microsite', as: :client_microsite
  get ':client_slug/:microsite_slug/:cms_page_slug' => 'page#preview_microsite'
  get ':slug' => 'page#cms'
  get ':slug/:type' => 'page#cms' 

  

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :users_group
  has_many :users, :through => :users_group

  has_many :survey_groups
  has_many :surveys, :through => :survey_groups

  has_many :pages_groups
  has_many :cms_pages, :through => :pages_groups

  has_many :microsites_group
  has_many :microsites, :through => :microsites_group

  validates :name, presence: true
  validates :name, format: { with: /\A[a-zA-Z0-9 _-]+\z/,
    message: "You can only use A-Z, a-z, 0-9, -, _ latters for group name." }
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 50 }  
  validates :name, uniqueness: true
  
  has_many :groups_variables
  has_many :variables, through: :groups_variables
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_permition
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  # layout "admin"
  layout "dashboard"

 
  autocomplete :group, :name, :full => true
  autocomplete :user, :username,:full => true


  # GET /groups
  # GET /groups.json
  def index
   # @groups = Group.all
    #puts current_user.groups.inspect
    if current_user.admin
      @groups = Group.all
      @survey = Survey.all
    else
      @groups = current_user.groups
    end
  
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group_variables = @group.groups_variables
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # GET /groups/#{@group.id}/unlink_user/#{user.id}
  def unlink_user
    ug = UsersGroup.where(:user_id => params[:user_id], :group_id => params[:group_id] )
    if ug != nil
      ug.map{|t| UsersGroup.destroy(t.id)  }
    end
    respond_to do |format|
      format.html{ redirect_to "/groups/#{params[:group_id]}" }
    end
  end

  # POST group_addExistingUsers_path
  def addExistingUsers
    @group = Group.find(params[:group_id])
    @message = ''
    @users = []
    if params[:task] = "add_users_to_grop" && params[:users] != ""
      users = params[:users]
      if users != nil
        users.first.split(",").each do |u|
          user = User.where(:username => u)
          if user != nil
            if !user.first.groups.exists?(@group.id)
              user.first.groups << @group
              @message = "#{user.first.username} successfully assigned to group #{@group.name}"
            else
              @message = "#{user.first.username} al ready exists in the group #{@group.name}"
            end
            
          end
        end
      end

      respond_to do |format|
        format.html { redirect_to @group, notice: @message }
        format.json { render json: user.first.groups, status: :created, notice: @message }
      end
    end
    
  end

  # GET group_addExistingUsers_path
  
  # def addExistingUsers
  #   @group = Group.find(params[:group_id])
  #   @errors = []
  #   @success = []
  #   @users = []
  #   if params[:task] = "add_users_to_grop" && params[:users] != ""
  #     users = params[:users]
  #     if users != nil
  #       users.first.split(",").each do |u|
  #         user = User.where(:username => u, :status => true )
  #         if user != nil
  #           if !user.first.groups.exists?(@group.id)
  #             user.first.groups << @group
  #             @success << "#{user.first.username} successfully assigned to group #{@group.name}" 
  #           else
  #             @errors << "#{user.first.username} al ready exists in the group #{@group.name}" 
  #           end
            
  #         end
  #       end
  #     end
  #   end
    
  # end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        @group.users << current_user
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET upload_users
  def upload_users
    @errors = []
    @success = []
    @dispatch = params[:csv_file]
    @group = Group.find(params[:group_id])
    count = 0
    if params[:task] == "Upload_users_csv"
      if @dispatch != nil && @dispatch.size

        CSV.foreach(@dispatch.path) do |row|
          if count > 0
             user = User.create(
                    :email => row[0], 
                    :password => row[1],
                    :username => row[2], 
                    :first_name => row[3], 
                    :sir_name => row[4], 
                    :last_name => row[5], 
                    :display_name => row[6], 
                    :status => true, 
                    :admin => false
                    ) 
             if user.errors.any?
               @errors << [user,user.errors.full_messages]
             else
              user.save
              @group.users << user
               @success << user
             end
             
          end
          count = count + 1
        end
      else
        @errors << [nil,["Invalid File!"]]
      end
    end

   # dd

    @group = Group.find(params[:group_id])
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        # @group.users << current_user
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :default_language)
    end

 
  def check_permition
    if current_user != nil
      if !current_user.can? params[:action].to_sym, :group
      flash[:alert] = [['You are not authorised to access this page']]
      redirect_to :controller => :admin, :action =>:home
      end
    end 
  end  

end

app/helpers/groups_helper.rb
module GroupsHelper

	def has_same_group res1, res2

	group1 = res1.groups.map{|g| g.id  }
	group2 = res2.groups.map{|g| g.id  }

	grouped = group1 & group2

		return 	grouped
		
	end

end

app/views/groups/edit.html.erb
<% content_for :title, t(:EDIT_GROUP) %>

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title"><%= t(:EDIT_GROUP) %></h3></div>

                <%= render 'form' %>
            </div> <!-- panel -->
        </div> <!-- col -->
    </div> <!-- End row -->


<%= link_to t(:show), @group %> |
<%= link_to t(:BACK_TO_GROUPS), groups_path %>

app/views/groups/show.html.erb
<% content_for :title, t(:GROUP_INFO) %>

<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t(:GROUP_INFO) %></h3>
      </div>
      <div class="panel-body">
        <p id="notice"><%= notice %></p>
        <p>
          <strong><%= t("NAME") %>:</strong>
          <%= @group.name %>
        </p>
        <p>
          <strong><%= t("DESCRIPTION") %>:</strong>
          <%= @group.description %>
        </p>

        <% if current_user.can? :edit, :group  %>
          <p><%= link_to t(:edit), edit_group_path(@group), class: 'group-grey-button' %></p>
        <% end %>
      </div>

      <div class="panel-heading">
        <h3 class="panel-title"><%= t("AL_USERS_OF_THIS_GROUP") %>
          <% if current_user.can? :upload_users, :group  %>
            <span class="pull-right">
              <%= link_to "Import CSV", group_upload_users_path(@group.id), 
              :class => "fancyajax"  %>
            </span>
          <% end %>
        </h3>
      </div>

      <div class="panel-body">
        <% if defined? @errors %>
          <div class="error-block">
            <% @errors.each do |e| %>
              <p style="color:red"><%= raw(e) %></p>
            <% end %>
          </div>
        <% end %>
        <% if defined? @success %>
          <div class="success-block">
            <% @success.each do |s| %>
              <p style="color:green"><%= raw(s) %></p>
            <% end %>
          </div>
        <% end %>
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="table-responsive">
               <table class="table">
                  <thead>
                    <tr>
                      <th><%= t("USER_NAME") %></th>
                      <th><%= t("FIRST_NAME") %></th>
                      <th><%= t("LAST_NAME") %></th>
                      <% if current_user.can? :unlink_user, :group  %> 
                      <th><%= t("UNLINK") %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% @group.users.each do |user| %>
                    <tr>
                      <td>
                        <%= link_to ('/admin/editUser/'+user.id.to_s) do %>
                          <%= user.username %>
                        <% end %>
                      </td>
                      <td><%= user.first_name %></td>
                      <td><%= user.last_name %></td>
                      <% if current_user.can? :unlink_user, :group  %> 
                      <td><%= link_to t("UNLINK"), 
                          "/groups/#{@group.id}/unlink_user/#{user.id}",
                      :data => { :confirm => "Are you Sure?" } %></td>
                      <% end %>
                    </tr>
                    <% end %>
                  </tbody>
               </table>
            </div>
          </div>
        </div>
        <% if current_user.can? :addExistingUsers, :group %> 
          <div class="row">
            <div class="col-lg-6 col-md-7 group-add-user-form">
              <%= form_for(@group, :url=> group_addExistingUsers_path(@group.id) ) do |f| %>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="search-pages">
                      <%= autocomplete_field_tag "users[]", "", autocomplete_user_username_groups_path,
                        class: 'group-add-user-input',
                        placeholder: 'Existing User Names(s)',
                        'data-delimiter' => ',', :multiple => true %>
                      <%= hidden_field_tag "task", "add_users_to_grop" %>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="submitbtn">
                        <%= button_tag(t(:ADD_USERS_TO_GROUP), 
                          data: { 
                          disable_with: t(:PLEASE_WAIT),
                          confirm: t(:ARE_YOU_SURE) }, class:"group-black-button") %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>  
      <!--
      <div class="panel-heading">
        <h3 class="panel-title"><%= t("IMPORT_MORE_USERS_IN_GROUP") %></h3>
      </div>
      <div class="panel-body">
      <% if current_user.can? :upload_users, :group  %> 
      <%= link_to "Import CSV", group_upload_users_path(@group.id), 
      :class => "fancyajax"  %>
      <% end %>
      </div>

      <div class="panel-heading">
        <h3 class="panel-title">Add Existing Users in this Group</h3>
      </div>
      <div class="panel-body">
      <% if current_user.can? :addExistingUsers, :group  %> 
        <h3 class="panel-title"><%= link_to t("ADD_EXISTING_USERS"), group_addExistingUsers_path(@group.id) %></h3>
        <% end %>
      </div>
      -->

      <div class="panel-heading">
        <h3 class="panel-title"><%= t("VARIABLES_FOR_THIS_GROUP") %>
        	<% if current_user.can? :addExistingUsers, :group  %> 
            <% if Variable.all.count > 0 %>
              <span class="pull-right">
                <%= link_to t(:ADD_NEW_VARIABLE), new_group_variable_path(@group.id) %>
              </span>
            <% end %>
          <% end %>
        </h3>
      </div>

      <div class="panel-body">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="table-responsive">
             <table class="table">
                <thead>
                   <tr>
                      <th><%= t("VARIABLE_NAME") %></th>
                      <th><%= t("TYPE") %></th>
                      <th>ID</th>
                      <th><%= t(:SHORT_CODE) %></th>
                      <th><%= t("VALUE") %></th>
                      <th colspan="2"></th>
                   </tr>
                </thead>
                <tbody>
                  <% @group_variables.each do |group_variable| %>
                  <tr>
                    <td><%= group_variable.variable.name %></td>
                    <td><%= group_variable.variable.vtype %></td>
                    <td><%= group_variable.variable.identifier %></td>
                    <td><%= get_shortcode(group_variable.variable) %></td>
                    <td><%= group_variable.value %></td>
                    <% if current_user.can? :edit, :groups_variables  %> 
                    <td><%= link_to t(:edit), edit_group_variable_path(group_variable.group, group_variable) %></td>
                    <% end %>
                    <% if current_user.can? :destroy, :groups_variables  %> 
                    <td><%= link_to 'Delete', group_variable_path(group_variable.group, group_variable), method: :delete, data: { confirm: t(:ARE_YOU_SURE) } %></td>
                    <% end %>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <% if Variable.all.count == 0 %>
          <p><%= t :NO_VARIABLES_DEFINED %></p>
        <% end %>
      </div>  

      <div class="panel-heading">
        <h3 class="panel-title"><%= t("MICROSITES_OF_THIS_GROUP")  %>
          <% if current_user.can? :addexistingmicrositestogroups, :microsites_groups  %> 
            <span class="pull-right">
              <%= link_to t("ADD_MICROSITE"),
                "/microsites_groups/addexistingmicrositestogroups/#{@group.id}",
                :target => "_BLANK", :class => "fancyajax" %>
            </span>
          <% end %>
        </h3>
      </div>

      <div class="panel-body">
        <div class="ajax-msg"></div>
      
        <div class="col-md-12 col-sm-12 col-xs-12">
          <ul class="mgroups-body">
            <% @group.microsites.each do |site|  %>
              <li class="microsite-item">
                <i class="fa fa-pencil-square-o" style="font-size:100px"></i>
                <ul class="controls">
                  <% if current_user.can? :unlinkmicrosite, :micrositegroup  %> 
                    <li>
                      <%= link_to t("UNLINK"),
                      "/microsites_groups/unlinkmicrosite/#{site.id}/#{@group.id}",
                      :data => { 
                        :confirm => "Confirm Unlink?",
                        "disable-with" => "Please Wait ..." }
                      %>
                    </li>
                  <% end %>
                  <!-- <li><%= link_to "CMS Pages", "/microsites_groups/listpagesbymicrositeandgroup/#{site.id}/#{@group.id}", :rel => "modal:open" %></li> -->
                </ul>
                <label><%= site.title %></label>
                <ul class="mgp-wrapper modal-control">
                  <li><label>CMS Pages</label></li>
                  <% if site.cms_pages.size > 0 %>
                    <% site.cms_pages.each do |page|  %>
                      <% if current_user.can? :managegroup, :cms_pages  %> 
                        <li class="page-item control-item" data-url="/cms_pages/<%= page.id %>/managegroup/<%= @group.id %>">
                          <i class="fa check 
                          <%= @group.cms_pages.exists?(page.id) ? 'fa-check-circle' : 'fa-times' %>"></i>
                          <%= page.title %>
                        </li>
                      <% else %>
                        <li class="page-item">
                          <%= page.title %>
                        </li>
                      <% end %>
                    <% end %>
                  <% else %>
                    <li class="age-item">No Page added yet!</li>
                  <% end %>
                </ul>
              </li>
              <% end %>
              <!--
              <li class="microsite-item">
                <ul class="controls">
                <% if current_user.can? :addexistingmicrositestogroups, :microsites_groups  %> 
                 <li>
                   <%= link_to t("ADD_EXISTING_MICROSITES_IN_THIS_GROUP"),
                   "/microsites_groups/addexistingmicrositestogroups/#{@group.id}",
                   :target => "_BLANK"    %>
                 </li>
                 <% end %>
                </ul>
                <i class="fa fa-plus-circle fa-6" style="font-size:100px"></i>
              </li>
              -->
          </ul>
        </div> 
      </div>
      <!--
      <div class="panel-heading">
        <h3 class="panel-title"><%= t("SURVEYS_OF_THIS_GROUP")  %></h3>
      </div>
      <div class="panel-body">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <ul class="mgroups-body sgroups">
            <% @group.surveys.each do |survey| %>
              <li class="microsite-item">
                <ul class="controls">
                  <li>
                  <% if current_user.can? :unlinkgroup, :survey_groups  %>
                  <%= link_to t("UNLINK"),
                  "/survey_groups/unlinkgroup/#{survey.id}/#{@group.id}", 
                  :data => { 
                    :confirm => "Confirm Unlink?",
                    "disable-with" => "Please Wait ..." } %>
                  </li>
                  <% end %>
                </ul>
              <i class="fa fa-pencil-square-o" style="font-size:100px"></i>
                 <label><%= survey.name  %></label>
              </li>
            <% end %>
            <li class="microsite-item">
                <ul class="controls">
                <% if current_user.can? :addexistingsurveystogroups, :survey_groups  %>
                 <li>
                   <%= link_to t("ADD_EXISTING_SURVEYS_IN_THIS_GROUP"),
                   "/survey_groups/addexistingsurveystogroups/#{@group.id}", 
                   :rel => "modal:open"    %>
                 </li>
                 <% end %>
                </ul>
                <i class="fa fa-plus-circle fa-6" style="font-size:100px"></i>
            </li>
          </ul>
        </div>
      </div>
      -->
    </div>
    <!-- panel -->
    <% if current_user.can? :edit, :group %>
    <%= link_to t(:edit), edit_group_path(@group) %>
    <% end %> |
    <% if current_user.can? :index, :group %>
    <%= link_to t(:Back), groups_path %>
    <% end %>
  </div> <!-- col -->
</div> <!-- End row -->