config/routes.rb
Rails.application.routes.draw do

  resources :uploaded_files

  resources :tableau_users

  resources :tableaus, path: '/tableau-dashboards'

  resources :extra_fields do
    collection do
      post :add_row, to: 'extra_fields#add_row'
      get 'remove_row/:group_id', to: 'extra_fields#remove_row'
      post :order_row, to: 'extra_fields#order_row'
    end
  end

  resources :pages_groups

  resources :microsites_groups

  get 'microsites_groups/unlinkmicrosite/:microsite_id/:group_id' => 'microsites_groups#unlinkmicrosite'

  get 'microsites_groups/addexistingmicrositestogroups/:group_id' => 'microsites_groups#addexistingmicrositestogroups'
  patch 'microsites_groups/addexistingmicrositestogroups/:group_id' => 'microsites_groups#addexistingmicrositestogroups'
  get 'microsites_groups/listpagesbymicrositeandgroup/:microsite_id/:group_id' => 'microsites_groups#listpagesbymicrositeandgroup'
  get 'microsites/unlink_client/:microsite_id/:client_id' => 'microsites#unlink_client'
  get 'microsites/:id/:pid/default_page' => 'microsites#default_page'

  resources :survey_groups
  get 'survey_groups/addexistingsurveystogroups/:group_id' => 'survey_groups#addexistingsurveystogroups'
  patch 'survey_groups/addexistingsurveystogroups/:group_id' => 'survey_groups#addexistingsurveystogroups'
  get 'survey_groups/unlinkgroup/:survey_id/:group_id' => 'survey_groups#unlinkgroup'

  resources :groups do
    get :autocomplete_group_name, :on => :collection
    get :autocomplete_user_username, :on => :collection

    get 'upload_users' 
    post 'upload_users'
    get 'unlink_user/:user_id' => 'groups#unlink_user'
    patch 'addExistingUsers'

    resources :variables, controller: :groups_variables
  end
  get 'file_mangers/all_files'

  get 'file_mangers/new_file'

  post 'file_mangers/create_file'

  resources :folders do
    resources :file_mangers
  end

  scope '/client' do
    get 'dashboard/:id' => 'page#client_dashboard'
    get 'tableau/:id/:task' => 'page#client_dashboard'
    get 'tableau/ticket' => 'page#client_dashboard'
    get ':id'=> 'admin#showClient'
    patch ':id' => 'admin#showClient'
  end

  scope '/take' do 
    get 'surveys' => 'played_surveys#surveys'
    get 'survey/:survey_id' => 'played_surveys#survey'
    get 'survey/:survey_id/:section_id' => 'played_surveys#survey'
    patch 'savesurvey/:section_id' => 'played_surveys#savesurvey'
  end

  resources :microsites do
    get :autocomplete_microsite_title, :on => :collection     
    member do

      get 'newcmspage/:template_id' => 'admin#newcmspage'
      
      get 'addexistingsurveys' => 'admin#addexistingsurveys'
      patch 'addexistingsurveys' => 'admin#addexistingsurveys'

      post 'create_cmspage' => 'admin#create_cmspage'
      patch 'create_cmspage' => 'admin#create_cmspage'
      get 'editpage/:cms_page_id/:template_id' => 'admin#editpage'
      patch 'update_cmspage/:cms_page_id' => 'admin#update_cmspage'

      get 'addexistingpages' => 'microsites#addexistingpages'
      patch 'addexistingpages' => 'microsites#addexistingpages'
      get 'unlinkcmspage/:page_id' => 'microsites#unlinkcmspage'

    end
  end

  resources :surveys do
    get :autocomplete_survey_name, :on => :collection 
  end
 
  post 'microsites/index' => 'microsites#index'
  get 'page/unpublished'

  mount Ckeditor::Engine => '/ckeditor'
  resources :played_surveys

  get 'page/show'
  resources :qfields
  get 'question/new/:section_id' =>'question#new'
  post 'question/new'
  post 'question/create'

  post 'qfield/delete/:id' => 'qfields#destroy'

  get 'admin/listroles' => 'admin#listroles'

  get 'admin/clients' => 'admin#listClients'

  get 'admin/editrole/:id/:role_id' => 'admin#editrole'

  patch 'admin/:id/updaterole' => 'admin#updaterole'

  get 'admin/listRoleCapability/:id/:role_id' => 'admin#listRoleCapability'

  post 'admin/setPermition/:id/:role_id' => 'admin#setPermition'

  get 'admin/unauthorised' => 'admin#unauthorised'

  get 'admin/taken_surveys' => 'admin#played_surveys'

  get 'question/field_type' => 'question#field_type'

  post 'question/field_type' => 'question#field_type'

  get 'admin/importuserscsv' => 'admin#importuserscsv'
  post 'admin/processuserscsv' => 'admin#processuserscsv'

  post 'admin/importusers' => 'admin#importusers'

  get 'admin/exportcsv' => 'admin#exportcsv'
  get 'admin/exportxls' => 'admin#exportxls'

  get 'admin/assign_survey' => 'admin#assign_survey_to_users'
  post 'admin/sending_group_invitation_users' => 'admin#sending_group_invitation_users'
 
  post '/admin/assign_survey_to_microsite' => 'admin#assign_survey_to_microsite'

  get 'admin/clients/new' => 'admin#newclient'
  get 'admin/clients/:id/edit' => 'admin#editclient'
  patch 'admin/clients/create' => 'admin#createclient'
  patch 'admin/clients/update' => 'admin#updateclient'

 
  
  resources :section
  resources :question
  resources :page
  resources :cms_page

  resources :cms_pages do
    get :autocomplete_cms_page_title, :on => :collection  
   post 'managegroup/:group_id' => 'cms_pages#managegroup'
  end

  resources :reports do
    collection do
      get :iframe
      get :javascript
      post :login
      get :logout
      get :access_denied
    end
  end

    

  post 'section/update/:id' => 'section#update'
  post 'section/create/:id' => 'section#create'
  get 'section/:id/new' => 'section#new'
  get 'section/:id/delete' => 'section#delete'

  get 'admin/microsites/:client_id' => 'admin#microsites'

  

  get 'question/:id/new' => 'question#new'

  post 'question/update' => 'question#update'

  get 'question/:id/delete/:survey_id' => 'question#delete'

  get 'question/:id/edit/:survey_id' => 'question#edit'
  post 'question/:id/edit/:survey_id' => 'question#edit'

  get 'admin/:id/editsurvey' => 'admin#editsurvey'
  get 'surveys/:id/destroy' => 'surveys#destroy'
  post 'surveys/:id/update' => 'surveys#update'

  get 'admin/clonepage/:page_id' => 'admin#clonepage'
  delete 'admin/deletepage/:page_id' => 'admin#deletepage'
  
  get  'surveyresults' => 'admin#survey_results'

 
  get 'admin/home' => 'admin#home'

  get 'admin/users' => 'admin#listUsers'
  put 'admin/edit_user_individual' => 'admin#edit_user_individual'
  post 'admin/bulkupdaterole'  =>  'admin#bulkupdaterole'
  get 'admin/delUser/:id' => 'admin#delUser'
  post 'admin/sendinvitationuser'  =>  'admin#sendinvitationuser'

  get 'admin/addUser', to: 'admin#addUser'
  post 'admin/addUser', to: 'admin#addUser'

  get 'admin/editUser/:id', to:'admin#editUser', as: :admin_editUser
  post 'admin/editUser/:id', to:'admin#editUser'

  get 'admin/upload_users', to: 'admin#upload_users'
  post 'admin/upload_users', to: 'admin#upload_users'

  get 'admin/addSurvey', to: 'admin#addSurvey'
  get 'admin/addSurvey/:client_id', to: 'admin#addSurvey'
  post 'admin/addSurvey', to: 'admin#addSurvey'
  get 'admin/manageSurvey', to: 'admin#manageSurvey'
  post 'admin/manageSurvey', to: 'admin#manageSurvey'
  get 'admin/buildsurvey/:id', to: 'admin#buildsurvey'
  get 'admin/survey_exports/:id', to: 'admin#survey_exports'
  get 'admin/unlinksurvey/:survey_id/:microsite_id', to: 'admin#unlinksurvey'

  resources :ext_users do
    resources :variables, controller: 'users_variables'
  end

  get 'two_factor_authentication', to: 'page#enterotp'
  get '/confirm/:id/:otp', to: 'page#check_two_factor_authentication'
  put 'check_two_factor_authentication', to: 'page#check_two_factor_authentication'
  post 'check_two_factor_authentication', to: 'page#check_two_factor_authentication'

  root 'admin#home' 
  devise_for :users, controllers: {  
      registrations:'users/registrations',
      sessions:'users/sessions',
      passwords:'users/passwords',
      confirmations:'users/confirmations',
      mailer:'users/mailer',
      shared:'users/shared',
      invitations:'users/invitations'
  }  do

  post 'two_factor_authentication' => 'users/sessions#check_two_factor_authentication'

  end
  
  resources :variables  

    
 

  get 'admin/accessmanage' => 'admin#accessmanage'

  post 'admin/create_slug' => 'admin#create_slug'
  get 'admin/newcmspage' => 'admin#newcmspage'
  get 'admin/newcmspage/:template_id' => 'admin#newcmspage'

  post 'admin/create_cmspage' => 'admin#create_cmspage'
  patch 'admin/create_cmspage' => 'admin#create_cmspage'

  get 'admin/listcmspages' => 'admin#listcmspages'
  post 'admin/listcmspages' => 'admin#listcmspages'
  get 'admin/editpage/:cms_page_id' => 'admin#editpage'

  get 'page_col/add_row/:page_id' => 'page#add_row'
  patch 'admin/update_cmspage/:cms_page_id' => 'admin#update_cmspage'
  get ':client_slug/:microsite_slug' => 'page#preview_microsite', as: :client_microsite
  get ':client_slug/:microsite_slug/:cms_page_slug' => 'page#preview_microsite'
  get ':slug' => 'page#cms'
  get ':slug/:type' => 'page#cms' 

  

end

app/models/users_variable.rb
class UsersVariable < ActiveRecord::Base
  validates :value, :presence => true
  validates_uniqueness_of :variable_id, :scope => :user_id

  belongs_to :user
  belongs_to :variable

  has_attached_file :value_file
  has_attached_file :value_image, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"

  do_not_validate_attachment_file_type :value_file
  validates_attachment_content_type :value_image, content_type: /\Aimage\/.*\Z/
  
  def value
    retval = case variable.vtype
      when 'image'
        value_image
      when 'file'
        value_file
      else
        value_text
      end
    retval
  end
end

app/controllers/users_variables_controller.rb
class UsersVariablesController < ApplicationController
  before_action :set_users_variable, only: [:show, :edit, :update, :destroy]

  layout "dashboard"
  include VariablesHelper
  # GET /users_variables
  # GET /users_variables.json
  def index
    @user_variables = UsersVariable.all
  end

  # GET /users_variables/1
  # GET /users_variables/1.json
  def show
  end

  # GET /users_variables/new
  def new
    puts '-------------------'
    puts ENV['AWS_ACCESS_KEY']
    @user_variable = UsersVariable.new(user_id: params[:ext_user_id])
  end

  # GET /users_variables/1/edit
  def edit
  end

  # POST /users_variables
  # POST /users_variables.json
  def create
    @user_variable = UsersVariable.new(users_variable_params)

    respond_to do |format|
      begin
        if @user_variable.save
          format.html { redirect_to admin_editUser_path(@user_variable.user), notice: 'User variable was successfully created.' }
          format.json { render :show, status: :created, location: @user_variable }
        else
          format.html { render :new, notice: @user_variable.errors }
          format.json { render json: @user_variable.errors, status: :unprocessable_entity }
        end
      rescue
        format.html { render :new }
        format.json { render json: @user_variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_variables/1
  # PATCH/PUT /users_variables/1.json
  def update
    respond_to do |format|
      if @user_variable.update(users_variable_params)
        format.html { redirect_to admin_editUser_path(@user_variable.user), notice: 'User variable was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_variable }
      else
        format.html { render :edit }
        format.json { render json: @user_variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_variables/1
  # DELETE /users_variables/1.json
  def destroy
    @user_variable.destroy
    respond_to do |format|
      format.html { redirect_to admin_editUser_path(@user_variable.user), notice: 'User variable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_variable
      @user_variable = UsersVariable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def users_variable_params
      params.require(:users_variable).permit(:user_id, :variable_id, :value_text, :value_file, :value_image)
    end
end

app/helpers/users_variables_helper.rb
module UsersVariablesHelper
  def value_field_type(variable)
    result = case variable.vtype
      when 'image'
        'image'
      when 'file'
        'file'
      else
        'text'
      end
  end
end

app/views/users_variables/_form.html.erb
<div class="panel-body">
  <p id="notice"><%= notice %></p>
  <%= form_for(@user_variable, url: url) do |f| %>
  <% if @user_variable.errors.any? %>
  <div id="error_explanation">
    <h5><%= t('errors.messages.not_saved', count: @user_variable.errors.count, resource: t(:user_variable)) %></h5>
    <ul>
      <% @user_variable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= f.hidden_field :user_id, value: @user_variable.user_id %>
  <div class="form-group">
    <%= f.label :variable_id, class: "col-md-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :variable_id, variable_names_collection, {}, {onchange: 'variable_name_changed(event);', class: "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-md-2 control-label"><%= t(:VARIABLE_TYPE) %></label>
    <div class="col-sm-10">
      <span id="variable_type" class="form-control"><%= Variable::Types[variable.vtype] %></span>
    </div>
  </div>
  <div class="form-group">
    <label class="col-md-2 control-label"><%= t(:VARIABLE_ID) %></label>
    <div class="col-sm-10">
      <span id="variable_identifier" class="form-control"><%= variable.identifier %></span>
    </div>
  </div>
  <div class="form-group" id="value_text_field"<% if value_field_type(variable) != 'text' %> style="display:none"<% end%>>
    <%= f.label :value_text, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_field :value_text, class: "form-control" %>
    </div>
  </div>
  <div class="form-group" id="value_file_field"<% if value_field_type(variable) != 'file' %> style="display:none"<% end%>>
    <%= f.label :value_file, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <div>
        <a href="<%= @user_variable.value_file.url %>"><%= @user_variable.value_file_file_name %></a>
      </div>
      <%= f.file_field :value_file, class: "form-control" %>

    </div>
  </div>
  <div class="form-group" id="value_image_field"<% if value_field_type(variable) != 'image' %> style="display:none"<% end%>>
    <%= f.label :value_image, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <div>
        <%= image_tag @user_variable.value_image(:medium), alt: '' %>
      </div>
      <%= f.file_field :value_image, class: "form-control" %>

    </div>
  </div>
  <div class="form-group m-b-0">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit t(:Save) , :class=> "btn btn-info waves-effect waves-light" %> 
    </div>
  </div>
  <% end %>
</div>
<!-- panel-body -->
<script type="text/javascript">
function variable_name_changed(event) {
  var id = event.target.value;
  $.ajax({
    url: "/variables/" + id + ".json",
    success: function(result) {
      $('#variable_type').html(result.vtype_name)
      $('#variable_identifier').html(result.identifier)
      if (result.vtype === 'image') {
        $('#value_text_field').hide();
        $('#value_file_field').hide();
        $('#value_image_field').show();
      } else if (result.vtype === 'file') {
        $('#value_text_field').hide();
        $('#value_image_field').hide();
        $('#value_file_field').show();
      } else {
        $('#value_file_field').hide();
        $('#value_image_field').hide();
        $('#value_text_field').show();
      }
    }
  });
}
</script>

app/views/users_variables/edit.html.erb
<% content_for :title, t(:EDIT_USER_VARIABLE) %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title trans-none"><%= t(:EDIT_USER_VARIABLE) %>
          <span class="pull-right">
          	<%= link_to t(:Back), admin_editUser_url(@user_variable.user) %>
          </span>
        </h3>
      </div>
      <%= render 'form', url: ext_user_variable_path(@user_variable.user, @user_variable), variable: @user_variable.variable %>
    </div>
  </div>
</div>
<!-- End row -->

app/views/users_variables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Variables</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_variables.each do |user_variable| %>
      <tr>
        <td><%= link_to t(:show), ext_user_variable_path(user_variable.user, user_variable) %></td>
        <td><%= link_to t(:edit), edit_ext_user_variable_path(user_variable.user, user_variable) %></td>
        <td><%= link_to t(:destroy), ext_user_variable_path(user_variable.user, user_variable), method: :delete, data: { confirm: t(:ARE_YOU_SURE) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User variable', new_ext_user_variable_path(params[:ext_user_id]) %>

app/views/users_variables/new.html.erb
<% content_for :title, t(:ADD_USER_VARIABLE) %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title trans-none"><%= t(:ADD_USER_VARIABLE) %>
        </h3>
      </div>
      <%= render 'form', url: ext_user_variables_path(user_id: params[:user_id]), variable: variable_names_collection.count ? Variable.find(variable_names_collection[0][1]) : {} %>
    </div>
  </div>
</div>
<!-- End row -->
<%= link_to t(:Back), admin_editUser_url(@user_variable.user) %>

app/views/users_variables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to t(:edit), edit_ext_user_variable_path(@user_variable.user, @user_variable) %> |
<%= link_to t(:Back), admin_editUser_url(@user_variable.user) %>