config/routes.rb
Rails.application.routes.draw do

  resources :uploaded_files

  resources :tableau_users

  resources :tableaus, path: '/tableau-dashboards'

  resources :extra_fields do
    collection do
      post :add_row, to: 'extra_fields#add_row'
      get 'remove_row/:group_id', to: 'extra_fields#remove_row'
      post :order_row, to: 'extra_fields#order_row'
    end
  end

  resources :pages_groups

  resources :microsites_groups

  get 'microsites_groups/unlinkmicrosite/:microsite_id/:group_id' => 'microsites_groups#unlinkmicrosite'

  get 'microsites_groups/addexistingmicrositestogroups/:group_id' => 'microsites_groups#addexistingmicrositestogroups'
  patch 'microsites_groups/addexistingmicrositestogroups/:group_id' => 'microsites_groups#addexistingmicrositestogroups'
  get 'microsites_groups/listpagesbymicrositeandgroup/:microsite_id/:group_id' => 'microsites_groups#listpagesbymicrositeandgroup'
  get 'microsites/unlink_client/:microsite_id/:client_id' => 'microsites#unlink_client'
  get 'microsites/:id/:pid/default_page' => 'microsites#default_page'

  resources :survey_groups
  get 'survey_groups/addexistingsurveystogroups/:group_id' => 'survey_groups#addexistingsurveystogroups'
  patch 'survey_groups/addexistingsurveystogroups/:group_id' => 'survey_groups#addexistingsurveystogroups'
  get 'survey_groups/unlinkgroup/:survey_id/:group_id' => 'survey_groups#unlinkgroup'

  resources :groups do
    get :autocomplete_group_name, :on => :collection
    get :autocomplete_user_username, :on => :collection

    get 'upload_users' 
    post 'upload_users'
    get 'unlink_user/:user_id' => 'groups#unlink_user'
    patch 'addExistingUsers'

    resources :variables, controller: :groups_variables
  end
  get 'file_mangers/all_files'

  get 'file_mangers/new_file'

  post 'file_mangers/create_file'

  resources :folders do
    resources :file_mangers
  end

  scope '/client' do
    get 'dashboard/:id' => 'page#client_dashboard'
    get 'tableau/:id/:task' => 'page#client_dashboard'
    get 'tableau/ticket' => 'page#client_dashboard'
    get ':id'=> 'admin#showClient'
    patch ':id' => 'admin#showClient'
  end

  scope '/take' do 
    get 'surveys' => 'played_surveys#surveys'
    get 'survey/:survey_id' => 'played_surveys#survey'
    get 'survey/:survey_id/:section_id' => 'played_surveys#survey'
    patch 'savesurvey/:section_id' => 'played_surveys#savesurvey'
  end

  resources :microsites do
    get :autocomplete_microsite_title, :on => :collection     
    member do

      get 'newcmspage/:template_id' => 'admin#newcmspage'
      
      get 'addexistingsurveys' => 'admin#addexistingsurveys'
      patch 'addexistingsurveys' => 'admin#addexistingsurveys'

      post 'create_cmspage' => 'admin#create_cmspage'
      patch 'create_cmspage' => 'admin#create_cmspage'
      get 'editpage/:cms_page_id/:template_id' => 'admin#editpage'
      patch 'update_cmspage/:cms_page_id' => 'admin#update_cmspage'

      get 'addexistingpages' => 'microsites#addexistingpages'
      patch 'addexistingpages' => 'microsites#addexistingpages'
      get 'unlinkcmspage/:page_id' => 'microsites#unlinkcmspage'

    end
  end

  resources :surveys do
    get :autocomplete_survey_name, :on => :collection 
  end
 
  post 'microsites/index' => 'microsites#index'
  get 'page/unpublished'

  mount Ckeditor::Engine => '/ckeditor'
  resources :played_surveys

  get 'page/show'
  resources :qfields
  get 'question/new/:section_id' =>'question#new'
  post 'question/new'
  post 'question/create'

  post 'qfield/delete/:id' => 'qfields#destroy'

  get 'admin/listroles' => 'admin#listroles'

  get 'admin/clients' => 'admin#listClients'

  get 'admin/editrole/:id/:role_id' => 'admin#editrole'

  patch 'admin/:id/updaterole' => 'admin#updaterole'

  get 'admin/listRoleCapability/:id/:role_id' => 'admin#listRoleCapability'

  post 'admin/setPermition/:id/:role_id' => 'admin#setPermition'

  get 'admin/unauthorised' => 'admin#unauthorised'

  get 'admin/taken_surveys' => 'admin#played_surveys'

  get 'question/field_type' => 'question#field_type'

  post 'question/field_type' => 'question#field_type'

  get 'admin/importuserscsv' => 'admin#importuserscsv'
  post 'admin/processuserscsv' => 'admin#processuserscsv'

  post 'admin/importusers' => 'admin#importusers'

  get 'admin/exportcsv' => 'admin#exportcsv'
  get 'admin/exportxls' => 'admin#exportxls'

  get 'admin/assign_survey' => 'admin#assign_survey_to_users'
  post 'admin/sending_group_invitation_users' => 'admin#sending_group_invitation_users'
 
  post '/admin/assign_survey_to_microsite' => 'admin#assign_survey_to_microsite'

  get 'admin/clients/new' => 'admin#newclient'
  get 'admin/clients/:id/edit' => 'admin#editclient'
  patch 'admin/clients/create' => 'admin#createclient'
  patch 'admin/clients/update' => 'admin#updateclient'

 
  
  resources :section
  resources :question
  resources :page
  resources :cms_page

  resources :cms_pages do
    get :autocomplete_cms_page_title, :on => :collection  
   post 'managegroup/:group_id' => 'cms_pages#managegroup'
  end

  resources :reports do
    collection do
      get :iframe
      get :javascript
      post :login
      get :logout
      get :access_denied
    end
  end

    

  post 'section/update/:id' => 'section#update'
  post 'section/create/:id' => 'section#create'
  get 'section/:id/new' => 'section#new'
  get 'section/:id/delete' => 'section#delete'

  get 'admin/microsites/:client_id' => 'admin#microsites'

  

  get 'question/:id/new' => 'question#new'

  post 'question/update' => 'question#update'

  get 'question/:id/delete/:survey_id' => 'question#delete'

  get 'question/:id/edit/:survey_id' => 'question#edit'
  post 'question/:id/edit/:survey_id' => 'question#edit'

  get 'admin/:id/editsurvey' => 'admin#editsurvey'
  get 'surveys/:id/destroy' => 'surveys#destroy'
  post 'surveys/:id/update' => 'surveys#update'

  get 'admin/clonepage/:page_id' => 'admin#clonepage'
  delete 'admin/deletepage/:page_id' => 'admin#deletepage'
  
  get  'surveyresults' => 'admin#survey_results'

 
  get 'admin/home' => 'admin#home'

  get 'admin/users' => 'admin#listUsers'
  put 'admin/edit_user_individual' => 'admin#edit_user_individual'
  post 'admin/bulkupdaterole'  =>  'admin#bulkupdaterole'
  get 'admin/delUser/:id' => 'admin#delUser'
  post 'admin/sendinvitationuser'  =>  'admin#sendinvitationuser'

  get 'admin/addUser', to: 'admin#addUser'
  post 'admin/addUser', to: 'admin#addUser'

  get 'admin/editUser/:id', to:'admin#editUser', as: :admin_editUser
  post 'admin/editUser/:id', to:'admin#editUser'

  get 'admin/upload_users', to: 'admin#upload_users'
  post 'admin/upload_users', to: 'admin#upload_users'

  get 'admin/addSurvey', to: 'admin#addSurvey'
  get 'admin/addSurvey/:client_id', to: 'admin#addSurvey'
  post 'admin/addSurvey', to: 'admin#addSurvey'
  get 'admin/manageSurvey', to: 'admin#manageSurvey'
  post 'admin/manageSurvey', to: 'admin#manageSurvey'
  get 'admin/buildsurvey/:id', to: 'admin#buildsurvey'
  get 'admin/survey_exports/:id', to: 'admin#survey_exports'
  get 'admin/unlinksurvey/:survey_id/:microsite_id', to: 'admin#unlinksurvey'

  resources :ext_users do
    resources :variables, controller: 'users_variables'
  end

  get 'two_factor_authentication', to: 'page#enterotp'
  get '/confirm/:id/:otp', to: 'page#check_two_factor_authentication'
  put 'check_two_factor_authentication', to: 'page#check_two_factor_authentication'
  post 'check_two_factor_authentication', to: 'page#check_two_factor_authentication'

  root 'admin#home' 
  devise_for :users, controllers: {  
      registrations:'users/registrations',
      sessions:'users/sessions',
      passwords:'users/passwords',
      confirmations:'users/confirmations',
      mailer:'users/mailer',
      shared:'users/shared',
      invitations:'users/invitations'
  }  do

  post 'two_factor_authentication' => 'users/sessions#check_two_factor_authentication'

  end
  
  resources :variables  

    
 

  get 'admin/accessmanage' => 'admin#accessmanage'

  post 'admin/create_slug' => 'admin#create_slug'
  get 'admin/newcmspage' => 'admin#newcmspage'
  get 'admin/newcmspage/:template_id' => 'admin#newcmspage'

  post 'admin/create_cmspage' => 'admin#create_cmspage'
  patch 'admin/create_cmspage' => 'admin#create_cmspage'

  get 'admin/listcmspages' => 'admin#listcmspages'
  post 'admin/listcmspages' => 'admin#listcmspages'
  get 'admin/editpage/:cms_page_id' => 'admin#editpage'

  get 'page_col/add_row/:page_id' => 'page#add_row'
  patch 'admin/update_cmspage/:cms_page_id' => 'admin#update_cmspage'
  get ':client_slug/:microsite_slug' => 'page#preview_microsite', as: :client_microsite
  get ':client_slug/:microsite_slug/:cms_page_slug' => 'page#preview_microsite'
  get ':slug' => 'page#cms'
  get ':slug/:type' => 'page#cms' 

  

end

app/models/microsites_group.rb
class MicrositesGroup < ActiveRecord::Base
  belongs_to :group
  belongs_to :microsite

  validates :group_id, :microsite_id, presence: true

  def self.updateMicrosite(params,microsite)
    groups = params[:groups]

     
    if groups != nil
      groups.each do |g|
        g = g.is_a?(Array) ? g.first : g
        if !microsite.groups.exists?(g.to_i)
          mg = MicrositesGroup.new()
          mg.microsite_id = microsite.id
          mg.group_id = g.to_i
          mg.save
        end
      end
    end 

   
    #now remove groups that 
    #was added before but now 
    #would like to remove by 
    #unchecking the checkbox
    microsite.groups.each do |g|
      remove = true
      groups.to_a.each do |pg|
        pg = pg.is_a?(Array) ? pg.first : pg
        if g.id == pg.to_i
          remove = false  
        end
      end
      if remove
        microsite.groups.destroy(g)
      end
    end
    
  end

end

app/controllers/microsites_groups_controller.rb
class MicrositesGroupsController < ApplicationController
  before_action :set_microsites_group, only: [:show, :edit, :update, :destroy]
  before_action :check_permition

  layout "dashboard"

  # GET /microsites_groups
  # GET /microsites_groups.json
  def index
    @microsites_groups = MicrositesGroup.all
  end

  # GET /microsites_groups/1
  # GET /microsites_groups/1.json
  def show
  end

  # GET /microsites_groups/new
  def new
    @microsites_group = MicrositesGroup.new
  end

  # GET /microsites_groups/1/edit
  def edit
  end

  # GET /microsites_groups/unlinkmicrosite/:microsite_id/:group_id
  def unlinkmicrosite
    microsites_group = MicrositesGroup.where(
      :microsite_id => params[:microsite_id],
      :group_id => params[:group_id]
      )

      if microsites_group != nil
        MicrositesGroup.destroy(microsites_group.map{ |mg| mg.id})
      end

      respond_to do |format|
        format.html{ redirect_to "/groups/#{params[:group_id]}" }
      end
  end

  #GET microsites_groups/listpagesbymicrositeandgroup
  def listpagesbymicrositeandgroup
    @group = Group.find(params[:group_id])
    @pages = CmsPage.where("id IN(?) AND microsite_id = (?)",
    @group.cms_pages.map{|p| p.id },params[:microsite_id])
    #, :group_id => params[:group_id],
    #:microsite_id => params[:microsite_id], :status => true
  end

  #GET microsites_groups/addexistingmicrositestogroups/:group_id
  def addexistingmicrositestogroups
    @group = Group.find(params[:group_id])
    @errors = []
    @success = []      

    if params[:task] == "assign-group-to-microsites"
       microsites = params[:microsites]  
       if microsites.size > 0
          microsites.first.split(",").each do |m|
            microsite = Microsite.find_by(:title => m)
            if microsite == nil
              @errors << "Microsite '#{m}' Not found in the System"
            else
              if(@group.microsites.exists?(microsite.id))
                @errors << "Microsite '#{microsite.title}' Already exists in this group"
              else
                mg = MicrositesGroup.new(:microsite_id => microsite.id,:group_id => @group.id )
                mg.save
                @success << "Microsite '#{microsite.title}' successfully added to group #{@group.name}"
              end
            end
          end    
       end     
    end

    @microsites = @group.microsites.size > 0 ? (Microsite.where("id NOT IN(?)",@group.microsites.map{|m| m.id})) : Microsite.all 
    @surveys = @group.surveys
  end


  # POST /microsites_groups
  # POST /microsites_groups.json
  def create
    @microsites_group = MicrositesGroup.new(microsites_group_params)
    respond_to do |format|
      if @microsites_group.save
        format.html { redirect_to @microsites_group, notice: 'Microsites group was successfully created.' }
        format.json { render :show, status: :created, location: @microsites_group }
      else
        format.html { render :new }
        format.json { render json: @microsites_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microsites_groups/1
  # PATCH/PUT /microsites_groups/1.json
  def update
    respond_to do |format|
      if @microsites_group.update(microsites_group_params)
        format.html { redirect_to @microsites_group, notice: 'Microsites group was successfully updated.' }
        format.json { render :show, status: :ok, location: @microsites_group }
      else
        format.html { render :edit }
        format.json { render json: @microsites_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microsites_groups/1
  # DELETE /microsites_groups/1.json
  def destroy
    @microsites_group.destroy
    respond_to do |format|
      format.html { redirect_to microsites_groups_url, notice: 'Microsites group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_microsites_group
      @microsites_group = MicrositesGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def microsites_group_params
      params[:microsites_group]
    end

  def check_permition
    if current_user != nil
      if !current_user.can? params[:action].to_sym, :micrositegroup
      flash[:alert] = [['You are not authorised to access this page']]
      redirect_to :controller => :admin, :action =>:home
      end
    end 
  end    


end

app/helpers/microsites_groups_helper.rb
module MicrositesGroupsHelper
end

app/views/microsites_groups/_form.html.erb
<%= form_for(@microsites_group) do |f| %>
  <% if @microsites_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.messages.not_saved', count: @microsites_group.errors.count, resource: t(:microsites_group)) %></h2>

      <ul>
      <% @microsites_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microsites_groups/addexistingmicrositestogroups.html.erb
<% content_for :title, t(:ASSIGNING_GROUP_TO_TARGET, group_name: @group.name, target: t(:Microsites)) %>
<div class="row">
<div class="col-sm-12">
<div class="panel panel-default">

	<div class="panel-heading">
		<h3 class="panel-title"><label><%= t(:ASSIGNING_GROUP_TO_TARGET, group_name: @group.name, target: t(:Microsites)) %>
	</div>

	<div class="panel-body">

		 <div class="error-block">
		 	<% @errors.each do |e|    %>
		 		<p style="color:red"><%= raw(e) %></p>
		 	<% end %>
		 </div>
		 <div class="success-block">
		 	<% @success.each do |s|    %>
		 		<p style="color:green"><%= raw(s) %></p>
		 	<% end %>
		 </div>


		 <div class="form-wrapper">
			<%= form_for(@group, 
			:url=>"/microsites_groups/addexistingmicrositestogroups/#{@group.id}") do |f| %>	
				<%= hidden_field_tag(:task, "assign-group-to-microsites" ) %>
				<div class="search-pages">
				  <label><%= t("SEARCH_MICROSITE_ASSIGN_TO_GROUP") %></label>
				  <%= autocomplete_field_tag "microsites[]", "", autocomplete_microsite_title_microsites_path,
				  'data-delimiter' => ',', :multiple => true %>
				</div>
				<div class="submitbtn" style="margin: 10px 0 20px">
				    <%= button_tag(t(:Save), 
				      data: { 
				      disable_with: t(:PLEASE_WAIT),
				      confirm: t(:ARE_YOU_SURE) }, class:"btn btn-info waves-effect waves-light") %>
				</div>
			<% end %>
		</div>

		  <div class="avaliavle-cms-pages">
			  <div class="title">
			  		<label><%= t("ASSIGN_GROUP_TO_MICROSITE_MSG") %>:</label>
			  </div>

			  <% @microsites.each do |site| %>
			  <p><%= site.title  %></p>
			  <% end %>
		  </div>



	</div>

</div>
</div>
 <%= link_to t(:Back), "/groups/#{@group.id}" %>
</div>	

app/views/microsites_groups/edit.html.erb
<% content_for :title, t(:EDIT_MICROSITES_GROUP) %>

<h1><%= t(:EDIT_MICROSITES_GROUP) %></h1>

<%= render 'form' %>

<%= link_to t(:show), @microsites_group %> |
<%= link_to t(:Back), microsites_groups_path %>

app/views/microsites_groups/index.html.erb
<% content_for :title, t(:LISTING_MICROSITES_GROUPS) %>

<p id="notice"><%= notice %></p>

<h1><%= t(:LISTING_MICROSITES_GROUPS) %></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microsites_groups.each do |microsites_group| %>
      <tr>
        <td><%= link_to t(:show), microsites_group %></td>
        <td><%= link_to t(:edit), edit_microsites_group_path(microsites_group) %></td>
        <td><%= link_to t(:destroy), microsites_group, method: :delete, data: { confirm: t(:ARE_YOU_SURE) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t(:NEW_MICROSITES_GROUP), new_microsites_group_path %>

app/views/microsites_groups/listpagesbymicrositeandgroup.html.erb
<%= @pages.inspect  %>

app/views/microsites_groups/new.html.erb
<% content_for :title, t(:NEW_MICROSITES_GROUP) %>

<h1><%= t(:NEW_MICROSITES_GROUP) %></h1>

<%= render 'form' %>

<%= link_to t(:Back), microsites_groups_path %>

app/views/microsites_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to t(:edit), edit_microsites_group_path(@microsites_group) %> |
<%= link_to t(:Back), microsites_groups_path %>